##############################################################################
#                             ePAS UI                                        #
# Configurazione per l'avvio della interfaccia Web di ePAS                   #
##############################################################################

services:
  epas-ui:
    image: ghcr.io/consiglionazionaledellericerche/epas-ui
    container_name: epas-ui-devel
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_CLIENTID=${NEXT_PUBLIC_CLIENTID}
      - NEXT_PUBLIC_EPAS_SERVICE=${NEXT_PUBLIC_EPAS_SERVICE}
      - NEXT_PUBLIC_OAUTH_CONFIG_URL=${NEXT_PUBLIC_OAUTH_CONFIG_URL}
      - NEXT_PUBLIC_OAUTH_ISSUER_URL=${NEXT_PUBLIC_OAUTH_ISSUER_URL}